-- Seed Countries
INSERT INTO countries (id, name, flag, currency, region) VALUES ('germany', 'Germany', '🇩🇪', 'EUR', 'Europe') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('canada', 'Canada', '🇨🇦', 'CAD', 'North America') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('australia', 'Australia', '🇦🇺', 'AUD', 'Oceania') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('uk', 'United Kingdom', '🇬🇧', 'GBP', 'Europe') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('ireland', 'Ireland', '🇮🇪', 'EUR', 'Europe') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('newzealand', 'New Zealand', '🇳🇿', 'NZD', 'Oceania') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('netherlands', 'Netherlands', '🇳🇱', 'EUR', 'Europe') ON CONFLICT (id) DO NOTHING;
INSERT INTO countries (id, name, flag, currency, region) VALUES ('sweden', 'Sweden', '🇸🇪', 'SEK', 'Europe') ON CONFLICT (id) DO NOTHING;

-- Seed Visa Programs
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('germany-student', 'germany', 'student_masters', true, 'Immediately', 'Full-time work allowed', true, 'After 3-5 years', '120 days or 240 half-days per year', '18 months job-seeker visa', 'Blocked account', '€11,208/year', 0, 3000, 'EUR', '4-12 weeks', 'German B2 or English IELTS 6.0+', 65, '2025-01-15', 'https://www.study-in-germany.de') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('germany-skilled', 'germany', 'skilled_worker', true, 'Immediately', 'Full-time work allowed', true, 'After 4 years', 'Full-time (40 hrs/week)', 'N/A', 'Employment contract required', 'Salary threshold applies', 0, 0, 'EUR', '4-12 weeks', 'German B1-B2 depending on occupation', 65, '2025-01-15', 'https://www.make-it-in-germany.com') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('germany-jobseeker', 'germany', 'job_seeker', false, 'Not allowed initially', 'N/A', false, 'N/A', 'No work allowed', '6-month visa to find employment', 'Blocked account', '€11,208', 0, 0, 'EUR', '4-8 weeks', 'German B1 minimum', 65, '2025-01-15', 'https://www.make-it-in-germany.com') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('canada-student', 'canada', 'student_masters', true, 'Immediately with open work permit', 'Full-time work allowed', true, 'After 1-2 years via Express Entry', '20 hrs/week off-campus', 'Up to 3 years PGWP', 'GIC + bank statement', 'CAD 20,635 + tuition', 15000, 50000, 'CAD', '8-16 weeks', 'IELTS 6.0+ overall', 70, '2025-01-15', 'https://www.canada.ca/en/immigration-refugees-citizenship.html') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('canada-skilled', 'canada', 'skilled_worker', true, 'Immediately', 'Full-time work allowed', true, '6-12 months via Express Entry', 'Full-time (40 hrs/week)', 'N/A', 'Settlement funds proof', 'CAD 13,757 (single applicant)', 0, 0, 'CAD', '6 months (Express Entry)', 'IELTS 6.0+ or CLB 7', 70, '2025-01-15', 'https://www.canada.ca/en/immigration-refugees-citizenship.html') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('australia-student', 'australia', 'student_masters', true, 'Immediately', '48 hrs per fortnight', true, 'After 2-3 years', '48 hrs per fortnight', '2-4 years depending on location', 'Bank statement', 'AUD 24,505 + tuition + travel', 20000, 55000, 'AUD', '4-12 weeks', 'IELTS 6.0+ overall', 75, '2025-01-15', 'https://immi.homeaffairs.gov.au') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('australia-skilled', 'australia', 'skilled_worker', true, 'Immediately', 'Full-time work allowed', true, '2-3 years on permanent visa', 'Full-time (40 hrs/week)', 'N/A', 'Points test + skills assessment', 'N/A (points-based)', 0, 0, 'AUD', '6-18 months', 'IELTS 6.0+ or PTE equivalent', 75, '2025-01-15', 'https://immi.homeaffairs.gov.au') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('uk-student', 'uk', 'student_masters', true, 'Immediately (if course 9+ months)', 'Full-time if course is PhD/research', true, 'After 5 years', '20 hrs/week during term', '2 years Graduate Route', 'Bank statement', '£1,334/month (up to 9 months) + tuition', 12000, 45000, 'GBP', '3-6 weeks', 'IELTS 6.5 (UKVI)', 80, '2025-01-15', 'https://www.gov.uk/student-visa') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('uk-skilled', 'uk', 'skilled_worker', true, 'Immediately', 'Full-time work allowed', true, 'After 5 years on Skilled Worker visa', 'Full-time (40 hrs/week)', 'N/A', 'Job offer from licensed sponsor', 'Salary threshold applies', 0, 0, 'GBP', '3-8 weeks', 'IELTS 4.0-5.5 depending on job', 80, '2025-01-15', 'https://www.gov.uk/skilled-worker-visa') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('ireland-student', 'ireland', 'student_masters', true, 'After 6 months', 'Full-time work allowed', true, 'After 5 years', '20 hrs/week during term, 40 hrs in holidays', '12 months Third Level Graduate Programme', 'Bank statement', '€10,000 + tuition', 10000, 35000, 'EUR', '4-8 weeks', 'IELTS 6.0+ or equivalent', 72, '2025-01-15', 'https://www.irishimmigration.ie') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('newzealand-student', 'newzealand', 'student_masters', true, 'Immediately', 'Full-time work allowed', true, 'After 2-3 years', '20 hrs/week during term', '1-3 years Post-Study Work Visa', 'Bank statement', 'NZD 20,000/year + tuition', 22000, 45000, 'NZD', '4-6 weeks', 'IELTS 6.0+ overall', 68, '2025-01-15', 'https://www.immigration.govt.nz') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('netherlands-student', 'netherlands', 'student_masters', true, 'Immediately', 'Part-time (16 hrs/week)', true, 'After 5 years', '16 hrs/week during term', '1 year orientation year (zoekjaar)', 'Bank statement', '€1,115/month', 2000, 20000, 'EUR', '2-4 weeks', 'IELTS 6.0+ or Dutch B2', 70, '2025-01-15', 'https://www.studyinholland.nl') ON CONFLICT (id) DO NOTHING;
INSERT INTO visa_programs (id, country_id, category, spouse_can_accompany, spouse_join_delay, spouse_work_rights, pr_pathway, time_to_pr, work_permit_hours, post_study_work_visa, financial_proof_type, financial_proof_amount, tuition_fee_min, tuition_fee_max, tuition_currency, processing_time, language_requirement, cost_of_living_index, last_updated, source_link) VALUES ('sweden-student', 'sweden', 'student_masters', true, 'Immediately', 'No work rights for dependents initially', true, 'After 4 years', 'No limit during studies', '12 months to seek employment', 'Bank statement', 'SEK 10,314/month', 0, 300000, 'SEK', '1-3 months', 'IELTS 6.0+ or Swedish B2', 72, '2025-01-15', 'https://www.universityadmissions.se') ON CONFLICT (id) DO NOTHING;
